export const CONFIG = Object.freeze({
  SLOT_MACHINE_SIZE: 3,
  REEL_SIZE: 60,
  REEL_OFFSET: 3,
  ANIMATION_DELAY: 1000,
  ANIMATION_DURATION: 2000,
  SYMBOL_QTY: 3,
  SPIN_BUTTON_DELAY: 800
});
